In [5]:
import numpy as np 
import pandas as pd

In [6]:
temp_df = pd.read_csv('IMDB Dataset.csv/IMDB Dataset.csv')

In [7]:
df = temp_df.iloc[:10000]
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [8]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [9]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(17)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
# Basic Preprocessing
# Remove tags
# lowercase
# remove stopwords

In [13]:
import re 
def remove_tags(raw_text):
    clean_text = re.sub(re.compile('<.*?>') , '' , raw_text)
    return clean_text

In [14]:
df['review'] = df['review'].apply(remove_tags)

In [15]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. The filming tec...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [16]:
df['review'] = df['review'].apply(lambda x: x.lower())

In [17]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [18]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in c:\users\asus\appdata\roaming\python\python313\site-packages (3.10.3)
Requirement already satisfied: defusedxml in c:\users\asus\appdata\roaming\python\python313\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\users\asus\appdata\roaming\python\python313\site-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in c:\users\asus\appdata\roaming\python\python313\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\asus\appdata\roaming\python\python313\site-packages (from nltk) (2026.7.19)
Requirement already satisfied: tqdm in c:\users\asus\appdata\roaming\python\python313\site-packages (from nltk) (4.70.0)
Requirement already satisfied: colorama in c:\users\asus\appdata\roaming\python\python313\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [20]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

df['review'] = df['review'].apply(lambda x : [item for item in x.split() if item not in sw_list]).apply(lambda x : " ".join(x))

In [21]:
df.head()

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production. filming technique...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically there's family little boy (jake) thi...  negative
4  petter mattei's "love time money" visually stu...  positive

In [22]:
X = df.iloc[: , 0:1]
y = df['sentiment']

In [23]:
X

                                                 review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [24]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: str

In [25]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [26]:
y

array([1, 1, 1, ..., 0, 0, 1], shape=(9983,))

In [27]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=1)

In [28]:
X_train.shape

(7986, 1)

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [31]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow , y_train)

GaussianNB()

In [32]:
y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test , y_pred)

0.6324486730095142

In [33]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train_bow , y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test , y_pred)

0.8507761642463696

In [ ]:
cv = CountVectorizer(ngram_range=(1,2) , max_features=5000)

### Using Tfidf

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [35]:
tfidf = TfidfVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review'])

In [36]:
rf = RandomForestClassifier()

rf.fit(X_train_tfidf , y_train)
y_pred = rf.predict(X_test_tfidf)
accuracy_score(y_test , y_pred)

0.8362543815723585

In [37]:
import gensim

ModuleNotFoundError: No module named 'gensim'

In [ ]:
from gensim.models import Word@Vec, KeyedVectors

In [ ]:
model = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin',binary=True,limit=500000)